define(function(){
$("#reg_header").load("../html/include/header.html");
$("#reg_footer").load("../html/include/footer.html");
$("#log_footer").load("../html/include/footer.html");
$("#log_header").load("../html/include/header.html");
$("#lis_footer").load("../html/include/footer.html");
$("#lis_header").load("../html/include/header.html");
$("#header").load("html/include/header1.html");
$("#footer").load("html/include/footer.html");
$("#car_header").load("../html/include/header.html");
$("#car_footer").load("../html/include/footer.html");
$("#pt_header").load("../html/include/header.html");
$("#pt_footer").load("../html/include/footer.html");
});
